// <auto-generated />
using CrudEFbyMigration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250524162231_AddDesignationToDb")]
    partial class AddDesignationToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollegeProject.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationAcronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesignationCode")
                        .HasColumnType("int");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesandResponsability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stream")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });
#pragma warning restore 612, 618
        }
    }
}
